### PR TITLE
Add missing features

### PR DESCRIPTION
**Pull request by ggwpez**
Somehow the command from the README does not build for me, going to put in the CI to see if it reproduces.

### CODE REVIEW

**Comment by rzadp** [comment]
The CI has [run out of disk space](https://github.com/paritytech/polkadot-sdk-parachain-template/actions/runs/10292197331/attempts/1?pr=10) on this run.

But it looks like the command has passed successfully before that happened:

Screenshot 2024-08-08 at 09 51 02

(also both work for me locally)

@ggwpez Is `cargo build` working for you, or is it just the `--release` one? Do you perhaps see similar errors as [here](https://github.com/paritytech/polkadot-sdk-minimal-template/issues/12)?

**Comment by ggwpez** [comment]
Yes it works now because i added the features. You can see the previous run here: https://github.com/paritytech/polkadot-sdk-parachain-template/actions/runs/10291282486/job/28483191721

So adding the features should fix it either way.

**Comment by rzadp** [comment]
> Yes it works now because i added the features.

Right, right, makes sense.
Running `cargo build --package parachain-template-node --release` without those fixes fails for me as well.

BUT - running `cargo build --release` on `master` is passing for me without any issues.
This is what I was running because I thought this built all the packages - including `parachain-template-node`.
Also tried `cargo build --release --all`.

Not sure what to do about next in terms of CI - do we have to check 6 variants in each template (3 packages, dev and release)?
This is very counterintuitive for me, how can building all packages pass but building one fails?

**Comment by ggwpez** [comment]
>This is very counterintuitive for me, how can building all packages pass but building one fails?

It is how cargo determines what features to enable. If you only build a single package then it may not enable all features since it only looks at that crate - not the whole workspace.  
I would suggest to add the `std` feature like i did here in the merge request. In the polkadot SDK we have a CI to check for this but its overkill here.

Additionally you can also change the build instructions in the readme just to `carbo build --release` since it is shorter.

**Comment by rzadp** [comment]
Sounds good, I think I'm getting it now.
I'll merge the PRs so that the templates are repaired, and will send a PR to `polkadot-sdk` with final changes.

**Comment by shawntabrizi** [comment]
>  Running cargo build --package parachain-template-node --release without those fixes fails for me as well.

Right, but this was the command that was included in the readme.... so it really should have been the one that was tested, or you should have put in the readme the steps you did which actually passed.

**Review by rzadp — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Pull request merged**
